### ISSUE TITLE
Multi-lib crashes the game

### ISSUE THREAD

**Issue by 3Snake3** [younggam/multi-lib#5]
When I want to see information about a block that has a code from multi-lib, the game crashes, writes that NumberValue is not defined.
Latest build 128.

**Comment by younggam** [comment]
Multi-lib must be outdated. 
Because of military duty, multi-lib is dead mod

**Comment by 3Snake3** [comment]
Will you update it?

**Comment by younggam** [comment]
well, the days for my duty left about 350. May not expect it to be updated

**Comment by 3Snake3** [comment]
@younggam I tried to fix the multi-crafter's code and I did it successfully. Can I publish the repaired version?

**Comment by younggam** [comment]
I dunno what actually 'publish' means, but you can release your own repo that based on multi-lib only if you clarify source and use gpl 3.0 license

**Comment by 3Snake3** [comment]
Ok, thanks. That's what I meant.
